typedef enum logic [4:0] {
    OP_ZERO         = 5'd0,
	OP_NEGATE       = 5'd1,
	OP_ADD          = 5'd2,
	OP_SUB          = 5'd3,
	OP_MULT         = 5'd4,
	OP_DIV          = 5'd5,
	OP_REM          = 5'd6,
	OP_AND          = 5'd7,
	OP_OR           = 5'd8,
	OP_NOT          = 5'd9,
	OP_XOR          = 5'd10,
	OP_A            = 5'd11,
    OP_B            = 5'd12,
	OP_SHL          = 5'd13,
	OP_SHR          = 5'd14,
    OP_EQ           = 5'd15,
    OP_NEQ          = 5'd16,
    OP_LT           = 5'd17,
    OP_GT           = 5'd18,
    OP_LE           = 5'd19,
    OP_GE           = 5'd20
} alu_op_t;